export const Users = [
  {
    id: 1,
    name: 'Alice Smith',
    email: 'alice.smith@example.com',
    role: 'admin',
    address: {
      street: '123 Main St',
      city: 'Anytown',
      state: 'CA',
      zipCode: '90210',
    },
    phone: '555-123-4567',
    isActive: true,
    joinedDate: '2023-01-15',
    department: 'Engineering',
    lastLogin: '2025-06-05T22:30:00Z',
    preferences: {
      theme: 'dark',
      notifications: true,
    },
    skills: ['JavaScript', 'React', 'Node.js'],
    profilePicture: 'https://example.com/profiles/alice.jpg',
  },
  {
    id: 2,
    name: 'Bob Johnson',
    email: 'bob.johnson@example.com',
    role: 'editor',
    address: {
      street: '456 Oak Ave',
      city: 'Smallville',
      state: 'NY',
      zipCode: '10001',
    },
    phone: '555-987-6543',
    isActive: true,
    joinedDate: '2022-11-01',
    department: 'Marketing',
    lastLogin: '2025-06-05T21:45:00Z',
    preferences: {
      theme: 'light',
      notifications: true,
    },
    skills: ['Content Writing', 'SEO', 'Social Media'],
    profilePicture: 'https://example.com/profiles/bob.jpg',
  },
  {
    id: 3,
    name: 'Charlie Brown',
    email: 'charlie.brown@example.com',
    role: 'viewer',
    address: {
      street: '789 Pine Ln',
      city: 'Gleason',
      state: 'TX',
      zipCode: '77001',
    },
    phone: '555-555-1212',
    isActive: false,
    joinedDate: '2024-03-20',
    department: 'Customer Support',
    lastLogin: '2025-06-04T10:00:00Z',
    preferences: {
      theme: 'light',
      notifications: false,
    },
    skills: ['Troubleshooting', 'Communication'],
    profilePicture: 'https://example.com/profiles/charlie.jpg',
  },
  {
    id: 4,
    name: 'Diana Prince',
    email: 'diana.prince@example.com',
    role: 'admin',
    address: {
      street: '101 Paradise Island',
      city: 'Themyscira',
      state: 'DC',
      zipCode: '20001',
    },
    phone: '555-333-2222',
    isActive: true,
    joinedDate: '2022-06-10',
    department: 'Executive',
    lastLogin: '2025-06-05T19:00:00Z',
    preferences: {
      theme: 'dark',
      notifications: true,
    },
    skills: ['Leadership', 'Strategic Planning', 'Project Management'],
    profilePicture: 'https://example.com/profiles/diana.jpg',
  },
  {
    id: 5,
    name: 'Eve Adams',
    email: 'eve.adams@example.com',
    role: 'viewer',
    address: {
      street: '222 Garden Rd',
      city: 'Eden',
      state: 'GA',
      zipCode: '30303',
    },
    phone: '555-777-8888',
    isActive: true,
    joinedDate: '2023-09-05',
    department: 'Human Resources',
    lastLogin: '2025-06-05T15:30:00Z',
    preferences: {
      theme: 'light',
      notifications: true,
    },
    skills: ['Recruitment', 'Employee Relations'],
    profilePicture: 'https://example.com/profiles/eve.jpg',
  },
  {
    id: 6,
    name: 'Frank White',
    email: 'frank.white@example.com',
    role: 'editor',
    address: {
      street: '333 Broadway',
      city: 'New York',
      state: 'NY',
      zipCode: '10012',
    },
    phone: '555-444-1111',
    isActive: true,
    joinedDate: '2023-02-28',
    department: 'Design',
    lastLogin: '2025-06-05T17:00:00Z',
    preferences: {
      theme: 'dark',
      notifications: true,
    },
    skills: ['UI/UX Design', 'Graphic Design', 'Figma'],
    profilePicture: 'https://example.com/profiles/frank.jpg',
  },
  {
    id: 7,
    name: 'Grace Kelly',
    email: 'grace.kelly@example.com',
    role: 'viewer',
    address: {
      street: '444 Hollywood Blvd',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90028',
    },
    phone: '555-666-9999',
    isActive: false,
    joinedDate: '2024-01-01',
    department: 'Public Relations',
    lastLogin: '2025-06-03T11:00:00Z',
    preferences: {
      theme: 'light',
      notifications: false,
    },
    skills: ['Media Relations', 'Event Planning'],
    profilePicture: 'https://example.com/profiles/grace.jpg',
  },
  {
    id: 8,
    name: 'Harry Potter',
    email: 'harry.potter@example.com',
    role: 'admin',
    address: {
      street: 'Privet Drive 4',
      city: 'Little Whinging',
      state: 'Surrey',
      zipCode: 'GU1 1AA',
    },
    phone: '555-222-3333',
    isActive: true,
    joinedDate: '2021-08-12',
    department: 'Magic Department',
    lastLogin: '2025-06-05T20:15:00Z',
    preferences: {
      theme: 'dark',
      notifications: true,
    },
    skills: ['Spellcasting', 'Defense Against Dark Arts', 'Leadership'],
    profilePicture: 'https://example.com/profiles/harry.jpg',
  },
  {
    id: 9,
    name: 'Ivy Green',
    email: 'ivy.green@example.com',
    role: 'editor',
    address: {
      street: '555 Garden St',
      city: 'Botanica',
      state: 'FL',
      zipCode: '33101',
    },
    phone: '555-888-7777',
    isActive: true,
    joinedDate: '2023-04-18',
    department: 'Research & Development',
    lastLogin: '2025-06-05T16:00:00Z',
    preferences: {
      theme: 'light',
      notifications: true,
    },
    skills: ['Data Analysis', 'Experiment Design'],
    profilePicture: 'https://example.com/profiles/ivy.jpg',
  },
  {
    id: 10,
    name: 'Jack Black',
    email: 'jack.black@example.com',
    role: 'viewer',
    address: {
      street: '666 Rock n Roll Rd',
      city: 'Music City',
      state: 'TN',
      zipCode: '37203',
    },
    phone: '555-000-1111',
    isActive: true,
    joinedDate: '2022-09-22',
    department: 'Entertainment',
    lastLogin: '2025-06-05T14:45:00Z',
    preferences: {
      theme: 'dark',
      notifications: true,
    },
    skills: ['Music', 'Acting', 'Comedy'],
    profilePicture: 'https://example.com/profiles/jack.jpg',
  },
  {
    id: 11,
    name: 'Karen Millen',
    email: 'karen.millen@example.com',
    role: 'admin',
    address: {
      street: '777 Fashion Ave',
      city: 'Style City',
      state: 'NY',
      zipCode: '10018',
    },
    phone: '555-111-2222',
    isActive: true,
    joinedDate: '2021-11-03',
    department: 'Sales',
    lastLogin: '2025-06-05T23:00:00Z',
    preferences: {
      theme: 'light',
      notifications: true,
    },
    skills: ['Sales Strategy', 'Negotiation', 'Client Management'],
    profilePicture: 'https://example.com/profiles/karen.jpg',
  },
  {
    id: 12,
    name: 'Liam Neeson',
    email: 'liam.neeson@example.com',
    role: 'editor',
    address: {
      street: '888 Taken Rd',
      city: 'Actionville',
      state: 'CA',
      zipCode: '90210',
    },
    phone: '555-333-4444',
    isActive: true,
    joinedDate: '2022-03-01',
    department: 'Security',
    lastLogin: '2025-06-05T22:00:00Z',
    preferences: {
      theme: 'dark',
      notifications: true,
    },
    skills: ['Tactical Operations', 'Crisis Management'],
    profilePicture: 'https://example.com/profiles/liam.jpg',
  },
  {
    id: 13,
    name: 'Mia Khalifa',
    email: 'mia.khalifa@example.com',
    role: 'viewer',
    address: {
      street: '999 Internet Pkwy',
      city: 'Webville',
      state: 'VA',
      zipCode: '20171',
    },
    phone: '555-555-6666',
    isActive: false,
    joinedDate: '2024-04-10',
    department: 'Content Moderation',
    lastLogin: '2025-06-04T09:00:00Z',
    preferences: {
      theme: 'light',
      notifications: false,
    },
    skills: ['Policy Enforcement', 'Content Review'],
    profilePicture: 'https://example.com/profiles/mia.jpg',
  },
  {
    id: 14,
    name: 'Noah Wyle',
    email: 'noah.wyle@example.com',
    role: 'admin',
    address: {
      street: '111 ER Way',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
    },
    phone: '555-777-8888',
    isActive: true,
    joinedDate: '2021-09-15',
    department: 'Medical',
    lastLogin: '2025-06-05T18:30:00Z',
    preferences: {
      theme: 'dark',
      notifications: true,
    },
    skills: ['Medicine', 'Patient Care', 'Diagnosis'],
    profilePicture: 'https://example.com/profiles/noah.jpg',
  },
  {
    id: 15,
    name: 'Olivia Wilde',
    email: 'olivia.wilde@example.com',
    role: 'viewer',
    address: {
      street: '222 House Blvd',
      city: 'Princeton',
      state: 'NJ',
      zipCode: '08540',
    },
    phone: '555-999-0000',
    isActive: true,
    joinedDate: '2023-07-25',
    department: 'Film Production',
    lastLogin: '2025-06-05T13:00:00Z',
    preferences: {
      theme: 'light',
      notifications: true,
    },
    skills: ['Directing', 'Acting', 'Screenwriting'],
    profilePicture: 'https://example.com/profiles/olivia.jpg',
  },
  {
    id: 16,
    name: 'Peter Pan',
    email: 'peter.pan@example.com',
    role: 'editor',
    address: {
      street: 'Neverland Island',
      city: 'Fantasy',
      state: 'GA',
      zipCode: '30303',
    },
    phone: '555-123-9876',
    isActive: true,
    joinedDate: '2022-05-19',
    department: 'Exploration',
    lastLogin: '2025-06-05T10:00:00Z',
    preferences: {
      theme: 'dark',
      notifications: true,
    },
    skills: ['Flying', 'Sword Fighting', 'Leadership'],
    profilePicture: 'https://example.com/profiles/peter.jpg',
  },
  {
    id: 17,
    name: 'Quinn Fabray',
    email: 'quinn.fabray@example.com',
    role: 'viewer',
    address: {
      street: '333 Glee St',
      city: 'Lima',
      state: 'OH',
      zipCode: '45801',
    },
    phone: '555-456-7890',
    isActive: false,
    joinedDate: '2024-02-14',
    department: 'Music Department',
    lastLogin: '2025-06-04T14:00:00Z',
    preferences: {
      theme: 'light',
      notifications: false,
    },
    skills: ['Singing', 'Performance', 'Teamwork'],
    profilePicture: 'https://example.com/profiles/quinn.jpg',
  },
  {
    id: 18,
    name: 'Rachel Zane',
    email: 'rachel.zane@example.com',
    role: 'admin',
    address: {
      street: '444 Law Office',
      city: 'New York',
      state: 'NY',
      zipCode: '10017',
    },
    phone: '555-789-0123',
    isActive: true,
    joinedDate: '2021-10-01',
    department: 'Legal',
    lastLogin: '2025-06-05T21:00:00Z',
    preferences: {
      theme: 'dark',
      notifications: true,
    },
    skills: ['Law', 'Negotiation', 'Contract Review'],
    profilePicture: 'https://example.com/profiles/rachel.jpg',
  },
  {
    id: 19,
    name: 'Steve Rogers',
    email: 'steve.rogers@example.com',
    role: 'editor',
    address: {
      street: '555 Avenger Tower',
      city: 'New York',
      state: 'NY',
      zipCode: '10017',
    },
    phone: '555-012-3456',
    isActive: true,
    joinedDate: '2022-01-20',
    department: 'Defense',
    lastLogin: '2025-06-05T19:30:00Z',
    preferences: {
      theme: 'light',
      notifications: true,
    },
    skills: ['Combat', 'Leadership', 'Tactics'],
    profilePicture: 'https://example.com/profiles/steve.jpg',
  },
  {
    id: 20,
    name: 'Tina Fey',
    email: 'tina.fey@example.com',
    role: 'viewer',
    address: {
      street: '666 Comedy Club',
      city: 'New York',
      state: 'NY',
      zipCode: '10019',
    },
    phone: '555-345-6789',
    isActive: true,
    joinedDate: '2023-06-12',
    department: 'Comedy',
    lastLogin: '2025-06-05T17:45:00Z',
    preferences: {
      theme: 'dark',
      notifications: true,
    },
    skills: ['Comedy Writing', 'Performing', 'Improvisation'],
    profilePicture: 'https://example.com/profiles/tina.jpg',
  },
];
